### PR TITLE
Update to new index structure

### PR DESCRIPTION
**Pull request by ronaldtse**
This PR updates to the new document repository structure where there is an index page to point to various documents.

However, it is not yet complete -- the index page currently doesn't pick up the generated XML RFC documents.

This is directly related to https://github.com/metanorma/relaton-cli/issues/52 -- @andrew2net can you please help fix in this PR? (the `Makefile` uses `relaton concatenate`) Thanks!

### CODE REVIEW

**Comment by andrew2net** [comment]
@ronaldtse I tried `make clean all` and got the error:
```
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'puppeteer'
Require stack:
- /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.11/bin/metanorma-pdf.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.11/bin/metanorma-pdf.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.11/bin/metanorma-pdf.js'
  ]
}
```
I istalled metanorma using homebrew
```
brew tap metanorma/metanorma
brew install metanorma
```
Do you know what can cause the error?

**Comment by ronaldtse** [comment]
puppeteer couldn’t be found. Are you using nvm or node directly? Maybe the PATH isn’t set to the node path. Look at the Travis file for hints.

**Comment by wsdwl** [comment]
different error message here: 

lmka-mm8a01dty3:csd-vpoll ts$ make clean all
rm -f cc-51006.html draft-calext-vpoll.html draft-york-vpoll.html cc-51006.pdf draft-calext-vpoll.pdf draft-york-vpoll.pdf cc-51006.txt draft-calext-vpoll.txt draft-york-vpoll.txt cc-51006.xml draft-calext-vpoll.xml draft-york-vpoll.xml cc-51006.xml draft-calext-vpoll.xml draft-york-vpoll.xml
if [ "x" == "x" ]; then bundle; fi
Traceback (most recent call last):
	2: from /Users/ts/.gem/ruby/2.5.3/bin/bundle:23:in `<main>'
	1: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
make: *** [bundle] Error 1

With the same setup/machine, I am able to build csd-admin-documents, but getting the same error on csd-calspam-bcp.

**Comment by ronaldtse** [comment]
@wsdwl for this specific error `can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)` it is due to the `bundler` gem version. If you run `gem install bundler` and try again, it should work.

**Comment by wsdwl** [comment]
unfortunatly not:

lmka-mm8a01dty3:csd-vpoll ts$ gem install bundler 
Successfully installed bundler-2.0.2
1 gem installed
lmka-mm8a01dty3:csd-vpoll ts$ make clean all
rm -f cc-51006.html draft-calext-vpoll.html draft-york-vpoll.html cc-51006.pdf draft-calext-vpoll.pdf draft-york-vpoll.pdf cc-51006.txt draft-calext-vpoll.txt draft-york-vpoll.txt cc-51006.xml draft-calext-vpoll.xml draft-york-vpoll.xml cc-51006.xml draft-calext-vpoll.xml draft-york-vpoll.xml
if [ "x" == "x" ]; then bundle; fi
Traceback (most recent call last):
	2: from /Users/ts/.gem/ruby/2.5.3/bin/bundle:23:in `<main>'
	1: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
make: *** [bundle] Error 1

**Comment by ronaldtse** [comment]
@wsdwl are you using `rbenv`? If so, can you try running `rbenv rehash`?

**Comment by wsdwl** [comment]
Never used before.

lmka-mm8a01dty3:csd-vpoll ts$ rbenv rehash
-bash: rbenv: command not found
lmka-mm8a01dty3:csd-vpoll ts$ brew install rbenv
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/bundle).
No changes to formulae.

==> Installing dependencies for rbenv: ruby-build
==> Installing rbenv dependency: ruby-build
==> Downloading https://github.com/rbenv/ruby-build/archive/v20190615.tar.gz
==> Downloading from https://codeload.github.com/rbenv/ruby-build/tar.gz/v20190615
######################################################################## 100.0%
==> ./install.sh
🍺  /usr/local/Cellar/ruby-build/20190615: 448 files, 224.6KB, built in 6 seconds
==> Installing rbenv
==> Downloading https://homebrew.bintray.com/bottles/rbenv-1.1.2.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring rbenv-1.1.2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/rbenv/1.1.2: 36 files, 65KB
lmka-mm8a01dty3:csd-vpoll ts$ rbenv rehash
lmka-mm8a01dty3:csd-vpoll ts$ make clean all
rm -f cc-51006.html draft-calext-vpoll.html draft-york-vpoll.html cc-51006.pdf draft-calext-vpoll.pdf draft-york-vpoll.pdf cc-51006.txt draft-calext-vpoll.txt draft-york-vpoll.txt cc-51006.xml draft-calext-vpoll.xml draft-york-vpoll.xml cc-51006.xml draft-calext-vpoll.xml draft-york-vpoll.xml
if [ "x" == "x" ]; then bundle; fi
Traceback (most recent call last):
	2: from /Users/ts/.gem/ruby/2.5.3/bin/bundle:23:in `<main>'
	1: from /Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/ts/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
make: *** [bundle] Error 1

No change

**Comment by wsdwl** [comment]
But move ahead with your original topic.

I am just here to let you know a different end user perspective :-)

**Comment by ronaldtse** [comment]
@wsdwl I've removed the `Gemfile.lock` version dependency. Can you pull and try again? Sorry...

**Comment by wsdwl** [comment]
pdf, html was created. Problems with IETF documents at the end:

[metanorma-ietf] Validation passed.
[metanorma-ietf] Error: unable to generate txt, the command `xml2rfc` is not found in path.
[metanorma-ietf] Error: unable to generate html, the command `xml2rfc` is not found in path.
VERSIONED_NAME=`grep :name: draft-calext-vpoll.adoc | cut -f 2 -d ' '`; \
	cp draft-calext-vpoll.txt ${VERSIONED_NAME}.txt && \
	idnits --verbose ${VERSIONED_NAME}.txt > draft-calext-vpoll.nits && \
	cp draft-calext-vpoll.nits ${VERSIONED_NAME}.nits && \
	cat ${VERSIONED_NAME}.nits
cp: draft-calext-vpoll.txt: No such file or directory
make: *** [draft-calext-vpoll.nits] Error 1

**Comment by ronaldtse** [comment]
@wsdwl To create RFC output you also need `xml2rfc`. Can you run this?

```sh
brew tap metanorma/metanorma
brew install metanorma
```

**Comment by andrew2net** [comment]
> puppeteer couldn’t be found. Are you using nvm or node directly? Maybe the PATH isn’t set to the node path. Look at the Travis file for hints.

@ronaldtse I'm using npm and node. What is nvm?
```
$ which node
/usr/local/bin/node

$ node -v
v12.4.0

$ which npm
/usr/local/bin/npm

$ npm -v
6.9.0
```

**Comment by wsdwl** [comment]
@ronaldtse No change as I was using this version before.

**Comment by ronaldtse** [comment]
@wsdwl then can you run:

```
pip install idnits
```

It will also install xml2rfc.

**Comment by ronaldtse** [comment]
@andrew2net can you install `puppeteer` directly via `npm install puppeteer`, and add `npm bin`'s output into your `PATH`?

**Comment by ronaldtse** [comment]
@wsdwl the Makefile has been updated, please also install `yq`. Thanks!

**Comment by andrew2net** [comment]
> @andrew2net can you install `puppeteer` directly via `npm install puppeteer`, and add `npm bin`'s output into your `PATH`?

@ronaldtse I've installed `puppeteer` directly via `npm install puppeteer` and added bin's path into `PATH`, but there isn't `puppeteer` in the bin folder. So the error remains.

**Comment by wsdwl** [comment]
@ronaldtse : For me it works now 👍

**Comment by andrew2net** [comment]
@ronaldtse now I go the error:
```
Error: No such file or directory @ rb_sysopen - /var/folders/qf/c8zl30p57pq5p7n1l5znydl80000gn/T/sources/draft-calext-vpoll.txt20190619-9318-1gtg6vf,
Not sure what to run? try: metanorma help
make: *** [sources/draft-calext-vpoll.xml] Error 2
```
Does the error related to this issue?

**Comment by ronaldtse** [comment]
> UPD It needs to install puppeteer global. I did it and the error has gone.

Thanks @andrew2net for this!

**Pull request merged**
